-------------------------------------------------------------------------------
Test set: com.google.code.morphia.issue194.IndexTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 10.326 sec <<< FAILURE!
TestDuplicate1(com.google.code.morphia.issue194.IndexTest)  Time elapsed: 5.223 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something : /127.0.0.1:27017/morphia_test
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
	at com.google.code.morphia.DatastoreImpl.ensureIndex(DatastoreImpl.java:245)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:309)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:275)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:339)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:332)
	at com.google.code.morphia.issue194.IndexTest.setUp(IndexTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused: connect
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 44 more

TestDuplicate1(com.google.code.morphia.issue194.IndexTest)  Time elapsed: 5.223 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something : /127.0.0.1:27017/morphia_test
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DB.command(DB.java:259)
	at com.mongodb.DB.command(DB.java:241)
	at com.mongodb.DB.command(DB.java:282)
	at com.mongodb.DB.command(DB.java:196)
	at com.mongodb.DBCollection.drop(DBCollection.java:838)
	at com.mongodb.DBApiLayer$MyCollection.drop(DBApiLayer.java:196)
	at com.google.code.morphia.TestBase.cleanup(TestBase.java:42)
	at com.google.code.morphia.TestBase.tearDown(TestBase.java:48)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused: connect
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 38 more

TestDuplicate2(com.google.code.morphia.issue194.IndexTest)  Time elapsed: 5.073 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something : /127.0.0.1:27017/morphia_test
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
	at com.google.code.morphia.DatastoreImpl.ensureIndex(DatastoreImpl.java:245)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:309)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:275)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:339)
	at com.google.code.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:332)
	at com.google.code.morphia.issue194.IndexTest.setUp(IndexTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused: connect
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 44 more

TestDuplicate2(com.google.code.morphia.issue194.IndexTest)  Time elapsed: 5.073 sec  <<< ERROR!
com.mongodb.MongoException$Network: can't call something : /127.0.0.1:27017/morphia_test
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
	at com.mongodb.DB.command(DB.java:259)
	at com.mongodb.DB.command(DB.java:241)
	at com.mongodb.DB.command(DB.java:282)
	at com.mongodb.DB.command(DB.java:196)
	at com.mongodb.DBCollection.drop(DBCollection.java:838)
	at com.mongodb.DBApiLayer$MyCollection.drop(DBApiLayer.java:196)
	at com.google.code.morphia.TestBase.cleanup(TestBase.java:42)
	at com.google.code.morphia.TestBase.tearDown(TestBase.java:48)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:35)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:146)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused: connect
	at com.mongodb.DBPort._open(DBPort.java:214)
	at com.mongodb.DBPort.go(DBPort.java:107)
	at com.mongodb.DBPort.call(DBPort.java:74)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
	... 38 more

